services:
  - type: web
    name: bera-hosting
    dockerfilePath: Dockerfile  # Points to root Dockerfile
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: bera-hosting-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    plan: standard  # Requires at least standard plan for PM2

databases:
  - name: bera-hosting-db
    plan: free
    databaseName: bera-hosting
