services:
  - type: web
    name: bera-hosting
    dockerfile: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DOCKER_SOCKET
        value: /var/run/docker.sock
      - key: GITHUB_CLIENT_ID
        value: your_github_client_id
      - key: GITHUB_CLIENT_SECRET
        value: your_github_client_secret
      - key: GITHUB_WEBHOOK_SECRET
        value: your_webhook_secret
