services:
  - type: web
    name: bera-hosting-backend
    env: node
    plan: free
    buildCommand: |
      cd backend && npm install
    startCommand: |
      cd backend && node server.js
    # Add this to disable Docker detection:
    dockerfilePath: ""
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: bera-hosting-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install
      cd frontend && npm run build
    startCommand: |
      cd frontend && npm run preview
    dockerfilePath: ""  # Disable Docker
    staticPath:
      buildOutputDirectory: frontend/dist
