name: Deploy Bera Hosting

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Backend
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --config ./backend/fly.toml"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
          
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Frontend
        uses: amondnet/vercel-action@v30
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          working-directory: frontend
